# Generated by Django 3.1.1 on 2020-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('user', models.CharField(default='', max_length=20)),
                ('booked', models.BooleanField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('genre', models.CharField(default='', max_length=20)),
                ('theatre', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('seats', models.IntegerField(default='')),
                ('seatsfilled', models.IntegerField(default='')),
                ('showtime', models.IntegerField(default='')),
            ],
        ),
    ]
